version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: mern-task-app-backend-dev-img
    container_name: mern-task-app-backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: mern-task-app-frontend-dev-img
    container_name: mern-task-app-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
